name: Gradle Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Gradle 8.3
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.3'

      - name: Grant execute permission for Gradle
        run: chmod +x subproject/gradlew

      - name: Run Gradle tests
        working-directory: ci
        run: ./gradlew test
